import React from 'react';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { NextIntlClientProvider } from 'next-intl';
import '../globals.css';
import { notFound } from 'next/navigation';
// import seo from '@/seo.config';
// import { DefaultSeo } from 'next-seo';

const workSans = Work_Sans({
  subsets: ['vietnamese', 'latin'],
});

export const metadata: Metadata = {
  title: 'Be Americans',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const { locale } = await params;
  let messages;
  try {
    messages = (
      await import(`@/locales/${locale}.json`)
    ).default;
  } catch (error) {
    notFound();
  }

  return (
    <>
      <NextIntlClientProvider
        locale={locale}
        messages={messages}
      >
        <html lang={locale}>
          <body
            className={`${workSans.className} antialiased`}
          >
            <Header />
            <div className="flex min-h-screen w-full flex-col relative">
              <main>{children}</main>
              <a
                className="fixed z-50 bottom-10 right-10"
                href="https://zalo.me/3791173160286577010"
                target="_blank"
                rel="noopener noreferrer"
              >
                <img
                  width="64"
                  height="64"
                  src="/zalo.png"
                  alt="zalo"
                  className="w-12 h-12 md:w-16 md:h-16"
                />
              </a>
            </div>
            <Footer />
          </body>
        </html>
      </NextIntlClientProvider>
    </>
  );
}
